var grid_columns =
        {
            "main": [
                {"field": "id", "width": "100px", "title": "ID"},
                {"field": "checkInTech", "title": "Check-In Tech"},
                {
                    "field": "checkInDate",
                    "title": "Check In Date",
                    "template": "#= kendo.toString(kendo.parseDate(checkInDate), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Check In Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "auditTech", "title": "Audit Tech"},
                {
                    "field": "auditDate",
                    "title": "Audit Date",
                    "template": "#= kendo.toString(kendo.parseDate(auditDate), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Audit Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "quantity", "title": "Quantity"},
                {"field": "commodityCode", "title": "Commodity Code"},
                {"field": "category", "title": "Category"},
                {"field": "description", "title": "Description"},
                {
                    "field": "boxOpenDate",
                    "title": "Box Open Date",
                    "template": "#= kendo.toString(kendo.parseDate(boxOpenDate), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Box Open Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {
                    "field": "boxCloseDate",
                    "title": "Box Close Date",
                    "template": "#= kendo.toString(kendo.parseDate(boxCloseDate), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Box Open Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "stsserial", "title": "STS Serial"},
                {"field": "available", "title": "Available"},
                {"field": "scrap", "title": "Scrap"},
                {"field": "manufacturer", "title": "Manufacturer"},
                {"field": "serial", "title": "Serial"},
                {"field": "model", "title": "Model"},
                {"field": "emc", "title": "EMC"},
                {"field": "year", "title": "Year"},
                {"field": "formFactor", "title": "Form Factor"},
                {"field": "cpu", "title": "CPU"},
                {"field": "cpuqty", "title": "CPU Qty"},
                {"field": "dataWidth", "title": "Data Width"},
                {"field": "cpuspeed", "title": "CPU Speed"},
                {"field": "cores", "title": "Data Width"},
                {"field": "auditHDDSerial", "title": "Audit HDD Serial"},
                {"field": "auditHDDModel", "title": "Audit HDD Model"},
                {"field": "auditHDDSize", "title": "Audit HDD Size"},
                {"field": "auditHDDStatus", "title": "Audit HDD Status"},
                {"field": "videoAdapter", "title": "Video Adapter"},
                {"field": "screenSize", "title": "Screen Size"},
                {"field": "stand", "title": "Stand"},
                {"field": "screenCondition", "title": "Screen Condition"},
                {"field": "plasticCondition", "title": "Plastic Condition"},
                {"field": "totalMemory", "title": "Total Memory"},
                {"field": "ramslots", "title": "RAM Slots"},
                {"field": "ramperSlot", "title": "RAM Per Slot"},
                {"field": "ramparts", "title": "RAM Part"},
                {"field": "rammodel", "title": "RAM Model"},
                {"field": "typeofRAM", "title": "Type of RAM"},
                {"field": "capacitor", "title": "Capacitor"},
                {"field": "battery", "title": "Battery"},
                {"field": "batteryHealth", "title": "Battery Health"},
                {"field": "acAdaptor", "title": "A/C Adaptor"},
                {"field": "camera", "title": "Camera"},
                {"field": "connections", "title": "Connections"},
                {"field": "dvddrive", "title": "DVD Drive"},
                {"field": "coaversion", "title": "COA Version"},
                {"field": "coaedition", "title": "COA Edition"},
                {"field": "customerID", "title": "Customer ID"},
                {"field": "lotID", "title": "Lot ID"},
                {"field": "customerAsset", "title": "Customer Asset"},
                {"field": "box", "title": "Box"},
                {"field": "location", "title": "Location"},
                {"field": "palette", "title": "Palette"},
                {
                    "field": "soldDate",
                    "title": "Sold Date",
                    "template": "#= kendo.toString(kendo.parseDate(soldDate), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Sold Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "soldHDDSerial", "title": "Sold HDD Serial"},
                {"field": "soldHDDModel", "title": "Sold HDD Model"},
                {"field": "soldHDDSize", "title": "Sold HDD Size"},
                {"field": "soldHDDSmart", "title": "Sold HDD Smart"},
                {"field": "buildOrder", "title": "Build Order"},
                {"field": "buildOS", "title": "Build OS"},
                {"field": "buildSKU", "title": "Build SKU"},
                {"field": "sku", "title": "SKU"},
                {"field": "notes", "title": "Notes"},
            ],
            "rma": [
                {"field": "id", "title": "ID"},
                {"field": "serial", "title": "Serial"},
                {"field": "orderNumber", "title": "Order Number"},
                {"field": "tech", "title": "Tech"},
                {"field": "manufacturer", "title": "Manufacturer"},
                {"field": "model", "title": "Model"},
                {"field": "intSerial", "title": "STS Serial"},
                {
                    "field": "dateProduced",
                    "title": "Date Produced",
                    "template": "#= kendo.toString(kendo.parseDate(dateProduced), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Date Produced: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {
                    "field": "dateProcessed",
                    "title": "Date Processed",
                    "template": "#= kendo.toString(kendo.parseDate(dateProcessed), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Date Processed: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "troubleCode", "title": "Trouble Code"},
                {"field": "hddNotes", "title": "HDD Notes"},
                {"field": "hddSize", "title": "HDD Size"},
                {"field": "hddSerial", "title": "HDD Serial"},
                {"field": "hddModel", "title": "HDD Model"},
                {"field": "memNotes", "title": "Mem Notes"},
                {"field": "sku", "title": "Sku"},
                {"field": "notes", "title": "Notes"},
            ],
            "lcd": [
                {"field": "id", "title": "ID"},
                {"field": "serial", "title": "Serial"},
                {"field": "manufacturer", "title": "Manufacturer"},
                {"field": "model", "title": "Model"},
                {"field": "screenSize", "title": "Screen Size"},
                {"field": "screenCondition", "title": "Screen Condition"},
                {"field": "intSerial", "title": "STS Serial"},
                {"field": "customerId", "title": "Customer ID"},
                {"field": "customerAsset", "title": "Customer Asset"},
                {"field": "lotId", "title": "Lot ID"},
                {"field": "palette", "title": "Palette"},
                {"field": "location", "title": "Location"},
                {"field": "box", "title": "Box"},
                {
                    "field": "dateIn",
                    "title": "Audit Date",
                    "template": "#= kendo.toString(kendo.parseDate(dateIn), 'MM/dd/yyyy') #",
                    "groupHeaderTemplate": "Audit Date: #=  kendo.toString(value, 'MM/dd/yyyy') #"
                },
                {"field": "notes", "title": "Notes"},
                {"field": "available", "title": "Available"},
                {"field": "stand", "title": "Stand"},
                {"field": "hours", "title": "Hours"},
            ]
        };


var grid_fields = {
    "main": {
        "checkInTech": {"type": "string"},
        "checkInDate": {"type": "date"},
        "auditTech": {"type": "string"},
        "auditDate": {"type": "date"},
        "quantity": {"type": "string"},
        "commodityCode": {"type": "string"},
        "category": {"type": "string"},
        "description": {"type": "string"},
        "boxOpenDate": {"type": "date"},
        "boxCloseDate": {"type": "date"},
        "stsserial": {"type": "string"},
        "available": {"type": "string"},
        "scrap": {"type": "string"},
        "manufacturer": {"type": "string"},
        "serial": {"type": "string"},
        "model": {"type": "string"},
        "emc": {"type": "string"},
        "year": {"type": "string"},
        "formFactor": {"type": "string"},
        "cpu": {"type": "string"},
        "cpuqty": {"type": "string"},
        "dataWidth": {"type": "string"},
        "cpuspeed": {"type": "string"},
        "cores": {"type": "string"},
        "auditHDDSerial": {"type": "string"},
        "auditHDDModel": {"type": "string"},
        "auditHDDSize": {"type": "string"},
        "auditHDDStatus": {"type": "string"},
        "videoAdapter": {"type": "string"},
        "screenSize": {"type": "string"},
        "stand": {"type": "string"},
        "screenCondition": {"type": "string"},
        "plasticCondition": {"type": "string"},
        "totalMemory": {"type": "string"},
        "ramslots": {"type": "string"},
        "ramperSlot": {"type": "string"},
        "ramparts": {"type": "string"},
        "rammodel": {"type": "string"},
        "typeofRAM": {"type": "string"},
        "capacitor": {"type": "string"},
        "battery": {"type": "string"},
        "batteryHealth": {"type": "string"},
        "acAdaptor": {"type": "string"},
        "camera": {"type": "string"},
        "connections": {"type": "string"},
        "dvddrive": {"type": "string"},
        "coaversion": {"type": "string"},
        "coaedition": {"type": "string"},
        "customerID": {"type": "string"},
        "lotID": {"type": "string"},
        "customerAsset": {"type": "string"},
        "box": {"type": "string"},
        "location": {"type": "string"},
        "palette": {"type": "string"},
        "soldDate": {"type": "date"},
        "soldHDDSerial": {"type": "string"},
        "soldHDDSize": {"type": "string"},
        "soldHDDSmart": {"type": "string"},
        "buildOrder": {"type": "string"},
        "buildOS": {"type": "string"},
        "buildSKU": {"type": "string"},
        "sku": {"type": "string"},
        "notes": {"type": "string"}
    },
    "rma": {
        "id": {"type": "number"},
        "tech": {"type": "string"},
        "orderNumber": {"type": "number"},
        "notes": {"type": "string"},
        "hddSerial": {"type": "string"},
        "intSerial": {"type": "string"},
        "dateProcessed": {"type": "date"},
        "dateProduced": {"type": "date"},
        "troubleCode": {"type": "string"},
        "manufacturer": {"type": "string"},
        "hddNotes": {"type": "string"},
        "serial": {"type": "string"},
        "memNotes": {"type": "string"},
        "model": {"type": "string"},
        "sku": {"type": "string"},
        "hddSize": {"type": "string"},
        "hddModel": {"type": "string"}
    },
    "lcd": {
        "id": {"type": "number"},
        "customerAsset": {"type": "string"},
        "dateIn": {"type": "date"},
        "hours": {"type": "string"},
        "notes": {"type": "string"},
        "screenCondition": {"type": "string"},
        "available": {"type": "string"},
        "lotId": {"type": "string"},
        "box": {"type": "string"},
        "manufacturer": {"type": "string"},
        "intSerial": {"type": "string"},
        "screenSize": {"type": "string"},
        "serial": {"type": "string"},
        "customerId": {"type": "string"},
        "model": {"type": "string"},
        "palette": {"type": "string"},
        "location": {"type": "string"},
        "stand": {"type": "string"}
    }
}

var data_type = {
    "main": [
        {text: "Check-in Date", value: "checkInDate"},
        {text: "Audit Date", value: "auditDate"},
        {text: "Sold Date", value: "soldDate"},
        {text: "Box Open Date", value: "boxOpenDate"},
        {text: "Box Close Date", value: "boxCloseDate"},
    ],
    "rma": [
        {text: "Date Processed", value: "dateProcessed"},
        {text: "Date Produced", value: "dateProduced"},
    ],
    "lcd": [
        {text: "Audit Date", value: "dateIn"},
    ]
}

var date_range = [
    {text: "7 days ago", value: "d7"},
    {text: "14 days ago", value: "d14"},
    {text: "30 days ago", value: "d30"},
    {text: "90 days ago", value: "d90"},
    {text: "1 year ago", value: "y1"}
]

var data_aggregate = [
    {text: "Sum", value: "sum"},
    {text: "Max", value: "max"},
    {text: "Min", value: "min"},
    {text: "Avg", value: "avg"}
]
